name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./Tiva_test/Debug

jobs:
  build-and-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: clean the project
      run: make clean
    - name: check build 
      run: make all
    - name: run tests
      run: make test
    - name: make clean
      run: make clean
