name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./app

jobs:
  build-and-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    # - name: install cppunit
    #   run: sudo apt install -y libcppunit-dev
    - name: make clean
      run: make clean
    - name: make all
      run: make all
    # - name: make test
    #   run: make test
    - name: make clean
      run: make clean
